# Generated by Django 3.2.6 on 2021-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
