# Generated by Django 3.2.6 on 2021-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefix', '0008_auto_20210925_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
