# Generated by Django 3.2.6 on 2021-11-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefix', '0009_alter_contact_us_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_requested',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
